# Generated by Django 5.2.4 on 2025-11-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('email', models.CharField(default='email@default.com', max_length=100)),
                ('telefone', models.CharField(default='000000000', max_length=100)),
            ],
            options={
                'ordering': ['id_marca'],
            },
        ),
        migrations.CreateModel(
            name='MarcaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='marcas.marca')),
            ],
            options={
                'indexes': [models.Index(fields=['marca', 'ip', 'data'], name='marcas_marc_marca_i_fc9c7c_idx'), models.Index(fields=['marca', 'data'], name='marcas_marc_marca_i_d1080f_idx')],
            },
        ),
    ]
