# Generated by Django 5.2.4 on 2025-11-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('img', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('destaque', models.BooleanField(default=False)),
                ('data_destaque', models.DateTimeField(blank=True, null=True)),
                ('n_visualizacoes', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('unissex', 'Unissex'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Unissex', 'Unissex')], default='unissex', max_length=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='marcas.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caminho', models.ImageField(upload_to='produtos/extras/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraImgs', to='roupas.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoTamanho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='roupas.produto')),
            ],
            options={
                'unique_together': {('produto', 'nome')},
            },
        ),
    ]
